config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :posts
  #resources :welcome, only: [:index] except
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image,     presence: true
  validates :text,      presence: true
  validates :likes,     presence: true, numericality: {message: 'must be a number'}
  validates :comments,  presence: true

  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      flash[:error] = 'Por favor revisar form'
      render :new #the page doesn't reload and the info doesn't get lost
      # redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)

    redirect_to posts_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :text, :likes, :comments)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700" rel="stylesheet">  
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label "Image URL", :image %>
  <%= f.text_field :image %>
  <%= f.label "Image text", :text %>
  <%= f.text_field :text %>
  <%= f.label "Image likes", :likes %>
  <%= f.text_field :likes %>
  <%= f.label "Image comments", :comment %>
  <%= f.text_area :comments, size: "60x12" %>
  <%= f.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
<div class="buttons">
  <a href="<%= root_path %>" class="btn btn--white">Home</a>
  <a href="<%= new_post_path %>" class="btn btn--green">Create new post</a>
</div>

<section class="section-posts">
  <% @posts.each do |post| %>
    <div class="post">
      <figure class="post__img-box">
        <img src="<%= post.image %>" class="post__img">
        <figcaption class="post__footer">
          <p class="post__likes"><%= post.likes %></p> 
          <p class="post__text"><%= post.text %></p>
        <figcaption> 
      </figure>
      <div class="post__comments">
        <p class="post__user"><strong>Nicolas</strong></p>  
        <p class="post__comment"><%= post.comments %></p>
      </div>
      <div class="buttons buttons--post">
        <a href="<%= post_path(post.id) %>" class="btn btn--lightblue">More...</a>
        <a href="<%= edit_post_path(post.id) %>" class="btn btn--lightgreen">Edit</a>
        <%= link_to 'Delete', post_path(post.id), method: :delete, class: 'btn btn--red' %>
      </div>
    </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<section class="section-form">

    <% if @post.errors.full_messages.length > 0 %>
      <div class="form__error">
        <% @post.errors.full_messages.each do |error| %>
          <p><%= error %></p>
        <% end %>
      </div>
    <% end %>

  <% flash.each do |val| %>
    #<%= val %>
  <% end %>
  
  <%= form_for @post, html: {class: 'form'} do |f| %>
  <div class="form__group">
    <%= f.label "Image URL", :image, class: 'form__label' %>
    <%= f.text_field :image, class: 'form__input' %>
  </div>
  <div class="form__group">
    <%= f.label "Image text", :text, class: 'form__label' %>
    <%= f.text_field :text, class: 'form__input' %>
  </div>
  <div class="form__group">
    <%= f.label "Image likes", :likes, class: 'form__label' %>
    <%= f.text_field :likes, class: 'form__input', type: 'number' %>
  </div>
  <div class="form__group">
    <%= f.label "Image comments", :comment, class: 'form__label' %>
    <%= f.text_area :comments, size: "60x12", class: 'form__input' %>
  </div>
  <%= f.submit "Create", class: 'btn btn--welcome btn--green' %>
<% end %>
</section>

app/views/posts/show.html.erb
<div class="buttons">
  <a href="<%= posts_path %>" class="btn btn--white">Home</a>
  <a href="<%= new_post_path %>" class="btn btn--green">Create new post</a>
</div>

<section class="section-posts">
  <div class="post">
    <figure class="post__img-box">
      <img src="<%= @post.image %>" class="post__img">
      <figcaption class="post__footer">
        <p class="post__likes"><%= @post.likes %></p> 
        <p class="post__text"><%= @post.text %></p>
      <figcaption> 
    </figure>
    <div class="post__comments">
      <p class="post__user"><strong>Nicolas</strong></p>  
      <p class="post__comment"><%= @post.comments %></p>
    </div>
    <div class="buttons buttons--post">
      <a href="<%= edit_post_path(@post.id) %>" class="btn btn--lightgreen">Edit</a>
      <%= link_to 'Delete', post_path(@post.id), method: :delete, class: 'btn btn--red' %>
    </div>
  </div>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<section class="section-welcome">
  <h1>Hello</h1>
  <a href="<%= posts_path %>" class="btn btn--blue btn--welcome">Posts</a>
</section>